config/routes.rb
Hrmsystem::Application.routes.draw do
  resources :faculties

  resources :users

  resources :research_group_members

  resources :research_groups

  root :to => 'rooms#index'

  resources :employees

  resources :rooms
  
  resources :departments, :only => [:index, :new, :create, :destroy, :show]
  
  resources :sessions, :only => [:new, :create, :destroy]
  
  get 'signin', to: 'sessions#new'
  get 'login', to: 'sessions#new'
  
  delete 'signout', to: 'sessions#destroy'
  delete 'logout', to: 'sessions#destroy'
  

  

end

app/models/research_group.rb
class ResearchGroup < ActiveRecord::Base
	has_many :research_group_members
	has_many :members, :through => :research_group_members, :source => :employee
	
	validates_presence_of :name
	validates_length_of :name, :minimum => 2
	
	def member_count
		members.length
	end
	
	def to_s
		name
	end
end

app/controllers/research_groups_controller.rb
class ResearchGroupsController < ApplicationController
  before_action :set_research_group, only: [:show, :edit, :update, :destroy]

  # GET /research_groups
  # GET /research_groups.json
  def index
    @research_groups = ResearchGroup.all
  end

  # GET /research_groups/1
  # GET /research_groups/1.json
  def show
  end

  # GET /research_groups/new
  def new
    @research_group = ResearchGroup.new
  end

  # GET /research_groups/1/edit
  def edit
  end

  # POST /research_groups
  # POST /research_groups.json
  def create
    @research_group = ResearchGroup.new(research_group_params)

    respond_to do |format|
      if @research_group.save
        format.html { redirect_to @research_group, notice: 'Research group was successfully created.' }
        format.json { render action: 'show', status: :created, location: @research_group }
      else
        format.html { render action: 'new' }
        format.json { render json: @research_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /research_groups/1
  # PATCH/PUT /research_groups/1.json
  def update
    respond_to do |format|
      if @research_group.update(research_group_params)
        format.html { redirect_to @research_group, notice: 'Research group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @research_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /research_groups/1
  # DELETE /research_groups/1.json
  def destroy
    @research_group.destroy
    respond_to do |format|
      format.html { redirect_to research_groups_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_research_group
      @research_group = ResearchGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def research_group_params
      params.require(:research_group).permit(:name)
    end
end

app/helpers/research_groups_helper.rb
module ResearchGroupsHelper
end

app/views/research_groups/_form.html.erb
<%= form_for(@research_group) do |f| %>
  <% if @research_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@research_group.errors.count, "error") %> prohibited this research_group from being saved:</h2>

      <ul>
      <% @research_group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/research_groups/edit.html.erb
<h1>Editing research_group</h1>

<%= render 'form' %>

<%= link_to 'Show', @research_group %> |
<%= link_to 'Back', research_groups_path %>

app/views/research_groups/index.html.erb
<h1>Listing research_groups</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @research_groups.each do |research_group| %>
      <tr>
        <td><%= link_to research_group.name, research_group %></td>
        <td><%= link_to 'Edit', edit_research_group_path(research_group) %></td>
        <td><%= link_to 'Destroy', research_group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Research group', new_research_group_path, class: "btn btn-primary" %>

app/views/research_groups/new.html.erb
<h1>New research_group</h1>

<%= render 'form' %>

<%= link_to 'Back', research_groups_path %>

app/views/research_groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @research_group.name %>
</p>

<p>
	<strong>Members (<%= @research_group.member_count %>):</strong>
	<ul>
		<% @research_group.members.each do |employee| %>
			<li><%= link_to employee, employee %></li>
		<% end %>
	</ul>
</p>

<%= link_to 'Edit', edit_research_group_path(@research_group), class: "btn" %>
<%= link_to 'Add employee', new_research_group_member_path(research_group_id: @research_group.id), class: "btn" %>
<%= link_to 'Back', research_groups_path, class: "btn" %>