config/routes.rb
Hrmsystem::Application.routes.draw do
  resources :faculties

  resources :users

  resources :research_group_members

  resources :research_groups

  root :to => 'rooms#index'

  resources :employees

  resources :rooms
  
  resources :departments, :only => [:index, :new, :create, :destroy, :show]
  
  resources :sessions, :only => [:new, :create, :destroy]
  
  get 'signin', to: 'sessions#new'
  get 'login', to: 'sessions#new'
  
  delete 'signout', to: 'sessions#destroy'
  delete 'logout', to: 'sessions#destroy'
  

  

end

app/models/research_group_member.rb
class ResearchGroupMember < ActiveRecord::Base
	belongs_to :employee
	belongs_to :research_group
end

app/controllers/research_group_members_controller.rb
class ResearchGroupMembersController < ApplicationController
  before_action :set_research_group_member, only: [:show, :edit, :update, :destroy]

  # GET /research_group_members
  # GET /research_group_members.json
  def index
    @research_group_members = ResearchGroupMember.all
  end

  # GET /research_group_members/1
  # GET /research_group_members/1.json
  def show
  end

  # GET /research_group_members/new
  def new
		@research_group = ResearchGroup.find(params[:research_group_id])
		redirect_to :back if @research_group.nil?
		
		@employees = Employee.all
		@research_group_member = ResearchGroupMember.new
  end

  # GET /research_group_members/1/edit
  def edit
  end

  # POST /research_group_members
  # POST /research_group_members.json
  def create

		group = ResearchGroup.find(research_group_member_params[:research_group_id])
		employee = Employee.find(research_group_member_params[:employee_id])

		if group.nil? or employee.nil? or group.members.include? employee
			redirect_to :back
		else
			group.members << employee
			redirect_to group
		end
  end

  # PATCH/PUT /research_group_members/1
  # PATCH/PUT /research_group_members/1.json
  def update
    respond_to do |format|
      if @research_group_member.update(research_group_member_params)
        format.html { redirect_to @research_group_member, notice: 'Research group member was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @research_group_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /research_group_members/1
  # DELETE /research_group_members/1.json
  def destroy
    @research_group_member.destroy
    respond_to do |format|
      format.html { redirect_to research_group_members_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_research_group_member
      @research_group_member = ResearchGroupMember.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def research_group_member_params
      params.require(:research_group_member).permit(:employee_id, :research_group_id)
    end
end

app/helpers/research_group_members_helper.rb
module ResearchGroupMembersHelper
end

app/views/research_group_members/_form.html.erb
<%= form_for(@research_group_member) do |f| %>
  <% if @research_group_member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@research_group_member.errors.count, "error") %> prohibited this research_group_member from being saved:</h2>

      <ul>
      <% @research_group_member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :employee_id %><br>
    <%= f.number_field :employee_id %>
  </div>
  <div class="field">
    <%= f.label :research_group_id %><br>
    <%= f.number_field :research_group_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/research_group_members/edit.html.erb
<h1>Editing research_group_member</h1>

<%= render 'form' %>

<%= link_to 'Show', @research_group_member %> |
<%= link_to 'Back', research_group_members_path %>

app/views/research_group_members/index.html.erb
<h1>Listing research_group_members</h1>

<table>
  <thead>
    <tr>
      <th>Employee</th>
      <th>Research group</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @research_group_members.each do |research_group_member| %>
      <tr>
        <td><%= research_group_member.employee_id %></td>
        <td><%= research_group_member.research_group_id %></td>
        <td><%= link_to 'Show', research_group_member %></td>
        <td><%= link_to 'Edit', edit_research_group_member_path(research_group_member) %></td>
        <td><%= link_to 'Destroy', research_group_member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Research group member', new_research_group_member_path %>

app/views/research_group_members/new.html.erb
<h1>New research_group_member</h1>

<%= form_for(@research_group_member) do |f| %>
  <% if @research_group_member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@research_group_member.errors.count, "error") %> prohibited this research_group_member from being saved:</h2>

      <ul>
      <% @research_group_member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :employee_id %><br>
    <%= f.select :employee_id, options_from_collection_for_select(@employees, :id, :to_s) %>
  </div>
  
	<%= f.hidden_field(:research_group_id,  :value => @research_group.id) %>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Back', research_groups_path, :class => "btn" %>

app/views/research_group_members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Employee:</strong>
  <%= @research_group_member.employee_id %>
</p>

<p>
  <strong>Research group:</strong>
  <%= @research_group_member.research_group_id %>
</p>

<%= link_to 'Edit', edit_research_group_member_path(@research_group_member) %> |
<%= link_to 'Back', research_group_members_path %>